"""
Comprehensive tests for Markdown rendering functionality.

Tests cover:
- Decision framework rendering with all sections
- Different analysis scenarios (compression, expansion, stable)
- Summary table generation
- Proper Markdown formatting
- Edge cases and missing data handling
"""

import pytest
from datetime import datetime
from src.utils.markdown_renderer import (
    render_decision_framework,
    render_summary_table,
    _render_header,
    _render_executive_summary,
    _render_detailed_analysis,
    _render_recommendations,
    _render_risk_factors,
    _render_next_steps,
    _render_mode_info,
    _render_footer
)


class TestDecisionFrameworkRendering:
    """Test suite for full decision framework rendering."""
    
    def test_complete_framework_compression_detected(self):
        """Test rendering with compression detected."""
        results = {
            "mode": "full",
            "symbol": "AAPL",
            "compression_detected": True,
            "compression_percentage": -25.5,
            "current_pe": 22.5,
            "historical_pe": 30.0,
            "industry_average": 28.0,
            "analysis": "Significant P/E compression detected.\nMay indicate market concerns.",
            "recommendations": [
                "Investigate recent earnings",
                "Check for company-specific news"
            ],
            "capabilities": ["Live data", "Industry comparison"],
            "data_sources": ["Perplexity API"],
            "limitations": [],
            "timestamp": "2025-11-13 12:00:00"
        }
        
        markdown = render_decision_framework(results)
        
        # Verify key sections are present
        assert "# P/E Compression Analysis Decision Framework" in markdown
        assert "AAPL" in markdown
        assert "🔴 **COMPRESSION DETECTED**" in markdown
        assert "-25.5%" in markdown
        assert "## Decision Recommendations" in markdown
        assert "## Risk Factors & Considerations" in markdown
        assert "## Next Steps" in markdown
        assert "## Analysis Details" in markdown
        
        # Verify specific content
        assert "Investigate recent earnings" in markdown
        assert "Full" in markdown or "full" in markdown
        assert "Generated by P/E Compression Analysis Skill" in markdown
    
    def test_framework_expansion_scenario(self):
        """Test rendering with P/E expansion."""
        results = {
            "mode": "basic",
            "symbol": "GOOGL",
            "compression_detected": False,
            "compression_percentage": -15.0,  # Expansion (negative compression)
            "current_pe": 28.0,
            "historical_pe": 24.0,
            "analysis": "P/E multiple has expanded, indicating increased market confidence."
        }
        
        markdown = render_decision_framework(results)
        
        assert "🟡 **P/E EXPANSION**" in markdown
        assert "15.0%" in markdown  # Absolute value
        assert "GOOGL" in markdown
    
    def test_framework_stable_valuation(self):
        """Test rendering with stable P/E ratio."""
        results = {
            "mode": "offline",
            "symbol": "MSFT",
            "compression_detected": False,
            "compression_percentage": -5.0,
            "current_pe": 25.0,
            "historical_pe": 24.0,
            "analysis": "Valuation remains stable."
        }
        
        markdown = render_decision_framework(results)
        
        assert "🟢 **STABLE VALUATION**" in markdown
        assert "MSFT" in markdown
    
    def test_framework_minimal_data(self):
        """Test rendering with minimal data provided."""
        results = {
            "mode": "basic",
            "symbol": "XYZ"
        }
        
        markdown = render_decision_framework(results)
        
        # Should still render without crashing
        assert "XYZ" in markdown
        assert "P/E Compression Analysis Decision Framework" in markdown
        assert "Basic" in markdown or "basic" in markdown


class TestHeaderRendering:
    """Test suite for header section rendering."""
    
    def test_header_basic(self):
        """Test basic header rendering."""
        header = _render_header("AAPL", "full")
        
        assert "# P/E Compression Analysis Decision Framework" in header
        assert "AAPL" in header
        assert "Full" in header
        assert "Generated" in header
        # Check for timestamp format (YYYY-MM-DD)
        assert "202" in header  # Year starts with 202x


class TestExecutiveSummaryRendering:
    """Test suite for executive summary rendering."""
    
    def test_summary_compression_detected(self):
        """Test summary with compression."""
        results = {
            "compression_detected": True,
            "compression_percentage": -30.0,
            "current_pe": 21.0,
            "historical_pe": 30.0
        }
        
        summary = _render_executive_summary(results)
        
        assert "🔴 **COMPRESSION DETECTED**" in summary
        assert "30.0%" in summary
        assert "21.00" in summary
        assert "30.00" in summary
    
    def test_summary_expansion(self):
        """Test summary with expansion."""
        results = {
            "compression_detected": False,
            "compression_percentage": -12.0,
            "current_pe": 28.0,
            "historical_pe": 25.0
        }
        
        summary = _render_executive_summary(results)
        
        assert "🟡 **P/E EXPANSION**" in summary
        assert "12.0%" in summary
    
    def test_summary_stable(self):
        """Test summary with stable valuation."""
        results = {
            "compression_detected": False,
            "compression_percentage": -3.0
        }
        
        summary = _render_executive_summary(results)
        
        assert "🟢 **STABLE VALUATION**" in summary
    
    def test_summary_missing_metrics(self):
        """Test summary with missing P/E values."""
        results = {
            "compression_detected": False,
            "compression_percentage": 0.0
        }
        
        summary = _render_executive_summary(results)
        
        # Should render without crashing
        assert "Executive Summary" in summary


class TestDetailedAnalysisRendering:
    """Test suite for detailed analysis section."""
    
    def test_analysis_with_text(self):
        """Test rendering with analysis text."""
        results = {
            "analysis": "Company shows strong fundamentals.\nMarket reaction seems overblown.",
            "current_pe": 20.0,
            "industry_average": 25.0
        }
        
        analysis = _render_detailed_analysis(results)
        
        assert "## Detailed Analysis" in analysis
        assert "Company shows strong fundamentals" in analysis
        assert "Market reaction seems overblown" in analysis
        assert "Industry Comparison" in analysis
        assert "25.00" in analysis
    
    def test_analysis_premium_valuation(self):
        """Test analysis with premium valuation warning."""
        results = {
            "analysis": "Analysis text",
            "current_pe": 35.0,
            "industry_average": 25.0  # >20% difference
        }
        
        analysis = _render_detailed_analysis(results)
        
        assert "⚠️  **Premium Valuation**" in analysis
        assert "significantly above" in analysis
    
    def test_analysis_discount_valuation(self):
        """Test analysis with discount valuation warning."""
        results = {
            "analysis": "Analysis text",
            "current_pe": 15.0,
            "industry_average": 25.0  # >20% difference
        }
        
        analysis = _render_detailed_analysis(results)
        
        assert "⚠️  **Discount Valuation**" in analysis
        assert "significantly below" in analysis
    
    def test_analysis_no_industry_data(self):
        """Test analysis without industry comparison data."""
        results = {
            "analysis": "Basic analysis text"
        }
        
        analysis = _render_detailed_analysis(results)
        
        assert "Basic analysis text" in analysis
        assert "Industry Comparison" not in analysis


class TestRecommendationsRendering:
    """Test suite for recommendations section."""
    
    def test_recommendations_provided(self):
        """Test rendering with provided recommendations."""
        results = {
            "recommendations": [
                "Review earnings report",
                "Check insider activity",
                "Assess growth trajectory"
            ]
        }
        
        recs = _render_recommendations(results)
        
        assert "## Decision Recommendations" in recs
        assert "1. Review earnings report" in recs
        assert "2. Check insider activity" in recs
        assert "3. Assess growth trajectory" in recs
    
    def test_recommendations_compression_default(self):
        """Test default recommendations for compression."""
        results = {
            "compression_detected": True
        }
        
        recs = _render_recommendations(results)
        
        assert "Investigate Fundamentals" in recs
        assert "Review Recent News" in recs
        assert "Consider Entry Point" in recs
    
    def test_recommendations_stable_default(self):
        """Test default recommendations for stable valuation."""
        results = {
            "compression_detected": False
        }
        
        recs = _render_recommendations(results)
        
        assert "Monitor Trends" in recs
        assert "Compare Peers" in recs


class TestRiskFactorsRendering:
    """Test suite for risk factors section."""
    
    def test_risk_factors_with_limitations(self):
        """Test risk factors with data limitations."""
        results = {
            "mode": "offline",
            "limitations": [
                "Using cached data from last week",
                "Limited to 5 peer companies"
            ]
        }
        
        risks = _render_risk_factors(results)
        
        assert "## Risk Factors & Considerations" in risks
        assert "Data Limitations:" in risks
        assert "cached data from last week" in risks
        assert "Limited to 5 peer companies" in risks
        assert "⚠️  **Data Quality Note**" in risks
        assert "cached data" in risks
    
    def test_risk_factors_full_mode(self):
        """Test risk factors in full mode (no data quality warning)."""
        results = {
            "mode": "full"
        }
        
        risks = _render_risk_factors(results)
        
        assert "General Considerations:" in risks
        assert "historical metrics" in risks
        # Should NOT have data quality warning for full mode
        assert "Data Quality Note" not in risks


class TestNextStepsRendering:
    """Test suite for next steps section."""
    
    def test_next_steps_compression(self):
        """Test next steps for compression scenario."""
        results = {
            "compression_detected": True
        }
        
        steps = _render_next_steps(results)
        
        assert "## Next Steps" in steps
        assert "- [ ] Deep dive into recent earnings reports" in steps
        assert "- [ ] Review analyst estimates" in steps
        assert "- [ ] Set price targets" in steps
    
    def test_next_steps_stable(self):
        """Test next steps for stable scenario."""
        results = {
            "compression_detected": False
        }
        
        steps = _render_next_steps(results)
        
        assert "- [ ] Continue monitoring P/E trends" in steps
        assert "- [ ] Review quarterly earnings" in steps


class TestModeInfoRendering:
    """Test suite for mode information section."""
    
    def test_mode_info_complete(self):
        """Test mode info with all data."""
        results = {
            "mode": "full",
            "capabilities": ["Live data", "Peer comparison", "Industry benchmarks"],
            "data_sources": ["Perplexity API", "Yahoo Finance"],
            "timestamp": "2025-11-13 12:00:00"
        }
        
        info = _render_mode_info(results)
        
        assert "## Analysis Details" in info
        assert "Full" in info
        assert "Capabilities:" in info
        assert "Live data" in info
        assert "Data Sources:" in info
        assert "Perplexity API" in info
        assert "2025-11-13 12:00:00" in info
    
    def test_mode_info_minimal(self):
        """Test mode info with minimal data."""
        results = {
            "mode": "basic"
        }
        
        info = _render_mode_info(results)
        
        assert "Basic" in info or "basic" in info


class TestFooterRendering:
    """Test suite for footer section."""
    
    def test_footer_content(self):
        """Test footer contains required elements."""
        footer = _render_footer()
        
        assert "Generated by P/E Compression Analysis Skill" in footer
        assert "v0.1.0" in footer
        assert "informational purposes only" in footer
        assert "not be considered investment advice" in footer


class TestSummaryTableRendering:
    """Test suite for summary table generation."""
    
    def test_summary_table_complete(self):
        """Test table with complete metrics."""
        results = {
            "symbol": "AAPL",
            "current_pe": 25.5,
            "historical_pe": 30.0,
            "compression_percentage": -15.0,
            "industry_average": 28.0,
            "mode": "full"
        }
        
        table = render_summary_table(results)
        
        assert "### Key Metrics" in table
        assert "| Metric | Value |" in table
        assert "| Symbol | AAPL |" in table
        assert "| Current P/E | 25.50 |" in table
        assert "| Historical P/E | 30.00 |" in table
        assert "| Compression % | -15.00 |" in table
        assert "| Industry Avg | 28.00 |" in table
        assert "| Mode | full |" in table
    
    def test_summary_table_partial(self):
        """Test table with partial metrics."""
        results = {
            "symbol": "XYZ",
            "current_pe": 20.0
        }
        
        table = render_summary_table(results)
        
        assert "| Symbol | XYZ |" in table
        assert "| Current P/E | 20.00 |" in table
        # Should not include missing metrics
        assert "Historical P/E" not in table


class TestFormattingQuality:
    """Test suite for Markdown formatting quality."""
    
    def test_no_empty_sections(self):
        """Ensure no completely empty sections are generated."""
        results = {
            "mode": "basic",
            "symbol": "TEST"
        }
        
        markdown = render_decision_framework(results)
        
        # Should not have consecutive blank lines (more than 2 newlines)
        assert "\n\n\n\n" not in markdown
    
    def test_proper_heading_hierarchy(self):
        """Test proper Markdown heading hierarchy."""
        results = {
            "mode": "basic",
            "symbol": "TEST",
            "compression_detected": False,
            "current_pe": 25.0,
            "industry_average": 24.0
        }
        
        markdown = render_decision_framework(results)
        
        # Main heading
        assert markdown.count("# P/E Compression Analysis") == 1
        # Section headings
        assert "## Executive Summary" in markdown
        assert "## Detailed Analysis" in markdown
        assert "## Decision Recommendations" in markdown
        # Subsection headings
        assert "### Industry Comparison" in markdown
    
    def test_list_formatting(self):
        """Test proper list formatting."""
        results = {
            "mode": "basic",
            "symbol": "TEST",
            "compression_detected": True
        }
        
        markdown = render_decision_framework(results)
        
        # Bulleted lists (checkboxes in next steps)
        assert "- [ ]" in markdown
        # Bulleted lists in risk factors
        assert "- P/E ratios" in markdown or "- Market sentiment" in markdown
        # Numbered lists in recommendations
        assert "1. **" in markdown


class TestEdgeCases:
    """Test suite for edge cases and error handling."""
    
    def test_empty_results(self):
        """Test rendering with empty results dictionary."""
        results = {}
        
        # Should not crash
        markdown = render_decision_framework(results)
        assert "P/E Compression Analysis Decision Framework" in markdown
    
    def test_none_values(self):
        """Test handling of None values."""
        results = {
            "symbol": None,
            "current_pe": None,
            "mode": None
        }
        
        # Should not crash
        markdown = render_decision_framework(results)
        assert "Decision Framework" in markdown
    
    def test_negative_compression_percentage(self):
        """Test handling of negative compression (expansion)."""
        results = {
            "compression_detected": False,
            "compression_percentage": -25.0
        }
        
        summary = _render_executive_summary(results)
        assert "25.0%" in summary  # Should show absolute value
    
    def test_very_long_analysis_text(self):
        """Test handling of very long analysis text."""
        long_text = "Analysis line.\n" * 100
        results = {
            "analysis": long_text
        }
        
        # Should not crash
        analysis = _render_detailed_analysis(results)
        assert "## Detailed Analysis" in analysis
        assert "Analysis line" in analysis


class TestIntegration:
    """Integration tests for complete rendering workflow."""
    
    def test_full_workflow_basic_mode(self):
        """Test complete workflow with basic mode."""
        results = {
            "mode": "basic",
            "symbol": "AAPL",
            "compression_detected": True,
            "compression_percentage": -20.0,
            "current_pe": 24.0,
            "historical_pe": 30.0,
            "industry_average": 28.0,
            "analysis": "Compression detected due to market concerns.",
            "capabilities": ["Industry comparison", "Historical analysis"],
            "data_sources": ["Static industry data"],
            "timestamp": "2025-11-13 12:00:00"
        }
        
        markdown = render_decision_framework(results)
        
        # Verify all major sections present
        sections = [
            "# P/E Compression Analysis Decision Framework",
            "## Executive Summary",
            "## Detailed Analysis",
            "## Decision Recommendations",
            "## Risk Factors & Considerations",
            "## Next Steps",
            "## Analysis Details",
            "Generated by P/E Compression Analysis Skill"
        ]
        
        for section in sections:
            assert section in markdown, f"Missing section: {section}"
        
        # Verify data quality warning for non-full mode
        assert "⚠️  **Data Quality Note**" in markdown
    
    def test_full_workflow_offline_mode(self):
        """Test complete workflow with offline mode."""
        results = {
            "mode": "offline",
            "symbol": "GOOGL",
            "compression_detected": False,
            "compression_percentage": -5.0,
            "current_pe": 26.0,
            "historical_pe": 25.0,
            "capabilities": ["Cached data", "Offline analysis"],
            "data_sources": ["Local cache"],
            "limitations": ["Data may be outdated"],
            "timestamp": "2025-11-13 12:00:00"
        }
        
        markdown = render_decision_framework(results)
        
        assert "Offline" in markdown
        assert "cached data" in markdown.lower()
        assert "Data may be outdated" in markdown


if __name__ == "__main__":
    pytest.main([__file__, "-v"])

